#!/usr/bin/env python3
# Generate the WebGL2 static-import shim for the wasm32-wasi build.
#
# love-wasi keeps upstream glad verbatim and only reseams its *loader*: instead
# of fetching GL function pointers from SDL_GL_GetProcAddress, glad's
# gladLoadGLLoader() populates its fp_* table from a callback that returns the
# address of a static wasm import — the host's WebGL2 context IS the GL surface
# (readme.md, "GL function loading"). This generator emits that callback plus
# one import declaration per GL entry point the opengl backend actually calls,
# with the signature taken from glad's own inline wrapper (so glad's pfn_* cast
# is ABI-correct). Entry points glad queries but WebGL2 lacks resolve to null,
# which glad reports as an absent feature — the faithful GLES 3.0 profile.
#
#   wasi/graphics/gen-gl-imports.py > wasi/graphics/gl-imports.cpp
#
# Re-run when the backend's GL call set changes; the output is committed so the
# diff stays the evidence (and the build needs no generator at compile time).
import re, subprocess, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
BACKEND = ROOT / "src/modules/graphics/opengl"
GLADFUNCS = ROOT / "src/libraries/glad/gladfuncs.hpp"

# 1. The GL entry points the backend references (member vars like glMode and
#    comment mentions are filtered out below by requiring a real glad wrapper).
called = set()
for cpp in sorted(BACKEND.glob("*.cpp")):
    for tok in re.findall(r"\bgl[A-Z][A-Za-z0-9]+\b", cpp.read_text()):
        called.add(tok)

# 2. glad's callable interface: name -> (return type, params), single-line inline.
wrappers = {}
wpat = re.compile(r'^inline\s+(.+?)\s+(gl\w+)\((.*?)\)\s*\{')
for line in GLADFUNCS.read_text().splitlines():
    m = wpat.match(line.strip())
    if m:
        wrappers[m.group(2)] = (m.group(1).strip(), m.group(3).strip())

got = sorted(n for n in called if n in wrappers)
skipped = sorted(n for n in called if n not in wrappers)
print(f"// {len(got)} imports generated; ignored non-calls: {' '.join(skipped)}",
      file=sys.stderr)

L = []
L.append('''/**
 * WebGL2 GL entry-point import shim for the wasm32-wasi (browser) build.
 *
 * GENERATED by wasi/graphics/gen-gl-imports.py from src/libraries/glad/gladfuncs.hpp
 * — do not edit by hand; re-run the generator if the backend's GL call set changes.
 *
 * love-wasi replaces glad's runtime GL loader (which fetches function pointers
 * from SDL_GL_GetProcAddress) with static wasm imports: the host's WebGL2
 * context IS the GL surface (readme.md, "GL function loading"). We do NOT
 * replace glad itself — upstream glad.cpp is compiled verbatim and its
 * gladLoadGLLoader() populates the fp_* table from the loader callback below,
 * so every glad header and every backend call site stays byte-unchanged. Only
 * the loader source changes: SDL proc-address -> address of a static import.
 *
 * Each import is declared with glad's own wrapper signature (so the fp_* cast
 * in gladLoadGLLoader is ABI-correct). Names glad queries but we don't provide
 * resolve to null, which glad reports as an absent entry point / feature — the
 * faithful WebGL2 (GLES 3.0) capability profile, host-reported.
 */
#include "libraries/glad/glad.hpp"
#include <cstring>

using namespace glad;

#define WGL_IMPORT(sym) __attribute__((import_module("love_gl"), import_name(sym)))

extern "C" {
''')

for n in got:
    ret, params = wrappers[n]
    L.append(f'WGL_IMPORT("{n}") {ret} wgl_{n}({params});')

L.append('''}

namespace love {
namespace graphics {
namespace opengl {

// The loader glad's gladLoadGLLoader() calls once per GL entry point. Returns
// the address of the matching static import, or null for anything the WebGL2
// host doesn't provide (glad then leaves that fp_* null / its GLAD flag false).
void *webgl_gl_loader(const char *name)
{
	static const struct { const char *name; void *fn; } table[] = {''')

for n in got:
    L.append(f'\t\t{{"{n}", (void *)&wgl_{n}}},')

L.append('''\t};
	for (const auto &e : table)
		if (std::strcmp(e.name, name) == 0)
			return e.fn;
	return nullptr;
}

} // opengl
} // graphics
} // love''')

sys.stdout.write('\n'.join(L) + '\n')
