/**
 * WebGL2 GL entry-point import shim for the wasm32-wasi (browser) build.
 *
 * GENERATED by wasi/graphics/gen-gl-imports.py from src/libraries/glad/gladfuncs.hpp
 * — do not edit by hand; re-run the generator if the backend's GL call set changes.
 *
 * love-wasi replaces glad's runtime GL loader (which fetches function pointers
 * from SDL_GL_GetProcAddress) with static wasm imports: the host's WebGL2
 * context IS the GL surface (readme.md, "GL function loading"). We do NOT
 * replace glad itself — upstream glad.cpp is compiled verbatim and its
 * gladLoadGLLoader() populates the fp_* table from the loader callback below,
 * so every glad header and every backend call site stays byte-unchanged. Only
 * the loader source changes: SDL proc-address -> address of a static import.
 *
 * Each import is declared with glad's own wrapper signature (so the fp_* cast
 * in gladLoadGLLoader is ABI-correct). Names glad queries but we don't provide
 * resolve to null, which glad reports as an absent entry point / feature — the
 * faithful WebGL2 (GLES 3.0) capability profile, host-reported.
 */
#include "libraries/glad/glad.hpp"
#include <cstring>

using namespace glad;

#define WGL_IMPORT(sym) __attribute__((import_module("love_gl"), import_name(sym)))

extern "C" {

WGL_IMPORT("glActiveTexture") void wgl_glActiveTexture(GLenum texture);
WGL_IMPORT("glAttachShader") void wgl_glAttachShader(GLuint program, GLuint shader);
WGL_IMPORT("glBindAttribLocation") void wgl_glBindAttribLocation(GLuint program, GLuint index, const GLchar* name);
WGL_IMPORT("glBindBuffer") void wgl_glBindBuffer(GLenum target, GLuint buffer);
WGL_IMPORT("glBindBufferBase") void wgl_glBindBufferBase(GLenum target, GLuint index, GLuint buffer);
WGL_IMPORT("glBindFramebuffer") void wgl_glBindFramebuffer(GLenum target, GLuint framebuffer);
WGL_IMPORT("glBindImageTexture") void wgl_glBindImageTexture(GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
WGL_IMPORT("glBindRenderbuffer") void wgl_glBindRenderbuffer(GLenum target, GLuint renderbuffer);
WGL_IMPORT("glBindTexture") void wgl_glBindTexture(GLenum target, GLuint texture);
WGL_IMPORT("glBindVertexArray") void wgl_glBindVertexArray(GLuint array);
WGL_IMPORT("glBlendEquationSeparate") void wgl_glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha);
WGL_IMPORT("glBlendFuncSeparate") void wgl_glBlendFuncSeparate(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
WGL_IMPORT("glBlitFramebuffer") void wgl_glBlitFramebuffer(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
WGL_IMPORT("glBufferData") void wgl_glBufferData(GLenum target, GLsizeiptr size, const void* data, GLenum usage);
WGL_IMPORT("glBufferStorage") void wgl_glBufferStorage(GLenum target, GLsizeiptr size, const void* data, GLbitfield flags);
WGL_IMPORT("glBufferSubData") void wgl_glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void* data);
WGL_IMPORT("glCheckFramebufferStatus") GLenum wgl_glCheckFramebufferStatus(GLenum target);
WGL_IMPORT("glClear") void wgl_glClear(GLbitfield mask);
WGL_IMPORT("glClearBufferData") void wgl_glClearBufferData(GLenum target, GLenum internalformat, GLenum format, GLenum type, const void* data);
WGL_IMPORT("glClearBufferSubData") void wgl_glClearBufferSubData(GLenum target, GLenum internalformat, GLintptr offset, GLsizeiptr size, GLenum format, GLenum type, const void* data);
WGL_IMPORT("glClearBufferfv") void wgl_glClearBufferfv(GLenum buffer, GLint drawbuffer, const GLfloat* value);
WGL_IMPORT("glClearBufferiv") void wgl_glClearBufferiv(GLenum buffer, GLint drawbuffer, const GLint* value);
WGL_IMPORT("glClearBufferuiv") void wgl_glClearBufferuiv(GLenum buffer, GLint drawbuffer, const GLuint* value);
WGL_IMPORT("glClearColor") void wgl_glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
WGL_IMPORT("glClearDepth") void wgl_glClearDepth(GLdouble depth);
WGL_IMPORT("glClearDepthf") void wgl_glClearDepthf(GLfloat d);
WGL_IMPORT("glClearStencil") void wgl_glClearStencil(GLint s);
WGL_IMPORT("glClientWaitSync") GLenum wgl_glClientWaitSync(GLsync sync, GLbitfield flags, GLuint64 timeout);
WGL_IMPORT("glColorMask") void wgl_glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
WGL_IMPORT("glCompileShader") void wgl_glCompileShader(GLuint shader);
WGL_IMPORT("glCompressedTexImage2D") void wgl_glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data);
WGL_IMPORT("glCompressedTexImage3D") void wgl_glCompressedTexImage3D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void* data);
WGL_IMPORT("glCompressedTexSubImage2D") void wgl_glCompressedTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void* data);
WGL_IMPORT("glCompressedTexSubImage3D") void wgl_glCompressedTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void* data);
WGL_IMPORT("glCopyBufferSubData") void wgl_glCopyBufferSubData(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
WGL_IMPORT("glCreateProgram") GLuint wgl_glCreateProgram();
WGL_IMPORT("glCreateShader") GLuint wgl_glCreateShader(GLenum type);
WGL_IMPORT("glCullFace") void wgl_glCullFace(GLenum mode);
WGL_IMPORT("glDebugMessageCallback") void wgl_glDebugMessageCallback(GLDEBUGPROC callback, const void* userParam);
WGL_IMPORT("glDebugMessageControl") void wgl_glDebugMessageControl(GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint* ids, GLboolean enabled);
WGL_IMPORT("glDeleteBuffers") void wgl_glDeleteBuffers(GLsizei n, const GLuint* buffers);
WGL_IMPORT("glDeleteFramebuffers") void wgl_glDeleteFramebuffers(GLsizei n, const GLuint* framebuffers);
WGL_IMPORT("glDeleteProgram") void wgl_glDeleteProgram(GLuint program);
WGL_IMPORT("glDeleteRenderbuffers") void wgl_glDeleteRenderbuffers(GLsizei n, const GLuint* renderbuffers);
WGL_IMPORT("glDeleteShader") void wgl_glDeleteShader(GLuint shader);
WGL_IMPORT("glDeleteSync") void wgl_glDeleteSync(GLsync sync);
WGL_IMPORT("glDeleteTextures") void wgl_glDeleteTextures(GLsizei n, const GLuint* textures);
WGL_IMPORT("glDeleteVertexArrays") void wgl_glDeleteVertexArrays(GLsizei n, const GLuint* arrays);
WGL_IMPORT("glDepthFunc") void wgl_glDepthFunc(GLenum func);
WGL_IMPORT("glDepthMask") void wgl_glDepthMask(GLboolean flag);
WGL_IMPORT("glDisable") void wgl_glDisable(GLenum cap);
WGL_IMPORT("glDisableVertexAttribArray") void wgl_glDisableVertexAttribArray(GLuint index);
WGL_IMPORT("glDiscardFramebufferEXT") void wgl_glDiscardFramebufferEXT(GLenum target, GLsizei numAttachments, const GLenum* attachments);
WGL_IMPORT("glDispatchCompute") void wgl_glDispatchCompute(GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
WGL_IMPORT("glDispatchComputeIndirect") void wgl_glDispatchComputeIndirect(GLintptr indirect);
WGL_IMPORT("glDrawArrays") void wgl_glDrawArrays(GLenum mode, GLint first, GLsizei count);
WGL_IMPORT("glDrawArraysIndirect") void wgl_glDrawArraysIndirect(GLenum mode, const void* indirect);
WGL_IMPORT("glDrawArraysInstanced") void wgl_glDrawArraysInstanced(GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
WGL_IMPORT("glDrawBuffers") void wgl_glDrawBuffers(GLsizei n, const GLenum* bufs);
WGL_IMPORT("glDrawElements") void wgl_glDrawElements(GLenum mode, GLsizei count, GLenum type, const void* indices);
WGL_IMPORT("glDrawElementsBaseVertex") void wgl_glDrawElementsBaseVertex(GLenum mode, GLsizei count, GLenum type, const void* indices, GLint basevertex);
WGL_IMPORT("glDrawElementsIndirect") void wgl_glDrawElementsIndirect(GLenum mode, GLenum type, const void* indirect);
WGL_IMPORT("glDrawElementsInstanced") void wgl_glDrawElementsInstanced(GLenum mode, GLsizei count, GLenum type, const void* indices, GLsizei instancecount);
WGL_IMPORT("glEnable") void wgl_glEnable(GLenum cap);
WGL_IMPORT("glEnableVertexAttribArray") void wgl_glEnableVertexAttribArray(GLuint index);
WGL_IMPORT("glFenceSync") GLsync wgl_glFenceSync(GLenum condition, GLbitfield flags);
WGL_IMPORT("glFinish") void wgl_glFinish();
WGL_IMPORT("glFlush") void wgl_glFlush();
WGL_IMPORT("glFlushMappedBufferRange") void wgl_glFlushMappedBufferRange(GLenum target, GLintptr offset, GLsizeiptr length);
WGL_IMPORT("glFramebufferRenderbuffer") void wgl_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
WGL_IMPORT("glFramebufferTexture2D") void wgl_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
WGL_IMPORT("glFramebufferTexture3D") void wgl_glFramebufferTexture3D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
WGL_IMPORT("glFramebufferTextureLayer") void wgl_glFramebufferTextureLayer(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
WGL_IMPORT("glFrontFace") void wgl_glFrontFace(GLenum mode);
WGL_IMPORT("glGenBuffers") void wgl_glGenBuffers(GLsizei n, GLuint* buffers);
WGL_IMPORT("glGenFramebuffers") void wgl_glGenFramebuffers(GLsizei n, GLuint* framebuffers);
WGL_IMPORT("glGenRenderbuffers") void wgl_glGenRenderbuffers(GLsizei n, GLuint* renderbuffers);
WGL_IMPORT("glGenTextures") void wgl_glGenTextures(GLsizei n, GLuint* textures);
WGL_IMPORT("glGenVertexArrays") void wgl_glGenVertexArrays(GLsizei n, GLuint* arrays);
WGL_IMPORT("glGenerateMipmap") void wgl_glGenerateMipmap(GLenum target);
WGL_IMPORT("glGetActiveUniform") void wgl_glGetActiveUniform(GLuint program, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
WGL_IMPORT("glGetAttribLocation") GLint wgl_glGetAttribLocation(GLuint program, const GLchar* name);
WGL_IMPORT("glGetCompressedTextureSubImage") void wgl_glGetCompressedTextureSubImage(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLsizei bufSize, void* pixels);
WGL_IMPORT("glGetError") GLenum wgl_glGetError();
WGL_IMPORT("glGetFloatv") void wgl_glGetFloatv(GLenum pname, GLfloat* data);
WGL_IMPORT("glGetIntegerv") void wgl_glGetIntegerv(GLenum pname, GLint* data);
WGL_IMPORT("glGetProgramInfoLog") void wgl_glGetProgramInfoLog(GLuint program, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
WGL_IMPORT("glGetProgramInterfaceiv") void wgl_glGetProgramInterfaceiv(GLuint program, GLenum programInterface, GLenum pname, GLint* params);
WGL_IMPORT("glGetProgramResourceName") void wgl_glGetProgramResourceName(GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei* length, GLchar* name);
WGL_IMPORT("glGetProgramiv") void wgl_glGetProgramiv(GLuint program, GLenum pname, GLint* params);
WGL_IMPORT("glGetRenderbufferParameteriv") void wgl_glGetRenderbufferParameteriv(GLenum target, GLenum pname, GLint* params);
WGL_IMPORT("glGetShaderInfoLog") void wgl_glGetShaderInfoLog(GLuint shader, GLsizei bufSize, GLsizei* length, GLchar* infoLog);
WGL_IMPORT("glGetShaderiv") void wgl_glGetShaderiv(GLuint shader, GLenum pname, GLint* params);
WGL_IMPORT("glGetString") const GLubyte* wgl_glGetString(GLenum name);
WGL_IMPORT("glGetTextureSubImage") void wgl_glGetTextureSubImage(GLuint texture, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, GLsizei bufSize, void* pixels);
WGL_IMPORT("glGetUniformLocation") GLint wgl_glGetUniformLocation(GLuint program, const GLchar* name);
WGL_IMPORT("glHint") void wgl_glHint(GLenum target, GLenum mode);
WGL_IMPORT("glInvalidateFramebuffer") void wgl_glInvalidateFramebuffer(GLenum target, GLsizei numAttachments, const GLenum* attachments);
WGL_IMPORT("glLinkProgram") void wgl_glLinkProgram(GLuint program);
WGL_IMPORT("glMapBufferRange") void* wgl_glMapBufferRange(GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
WGL_IMPORT("glMemoryBarrier") void wgl_glMemoryBarrier(GLbitfield barriers);
WGL_IMPORT("glObjectLabel") void wgl_glObjectLabel(GLenum identifier, GLuint name, GLsizei length, const GLchar* label);
WGL_IMPORT("glPixelStorei") void wgl_glPixelStorei(GLenum pname, GLint param);
WGL_IMPORT("glPolygonMode") void wgl_glPolygonMode(GLenum face, GLenum mode);
WGL_IMPORT("glPopDebugGroup") void wgl_glPopDebugGroup();
WGL_IMPORT("glPopDebugGroupKHR") void wgl_glPopDebugGroupKHR();
WGL_IMPORT("glPopGroupMarkerEXT") void wgl_glPopGroupMarkerEXT();
WGL_IMPORT("glPushDebugGroup") void wgl_glPushDebugGroup(GLenum source, GLuint id, GLsizei length, const GLchar* message);
WGL_IMPORT("glPushDebugGroupKHR") void wgl_glPushDebugGroupKHR(GLenum source, GLuint id, GLsizei length, const GLchar* message);
WGL_IMPORT("glPushGroupMarkerEXT") void wgl_glPushGroupMarkerEXT(GLsizei length, const GLchar* marker);
WGL_IMPORT("glReadBuffer") void wgl_glReadBuffer(GLenum src);
WGL_IMPORT("glReadPixels") void wgl_glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void* pixels);
WGL_IMPORT("glRenderbufferStorage") void wgl_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
WGL_IMPORT("glRenderbufferStorageMultisample") void wgl_glRenderbufferStorageMultisample(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
WGL_IMPORT("glResolveMultisampleFramebufferAPPLE") void wgl_glResolveMultisampleFramebufferAPPLE();
WGL_IMPORT("glScissor") void wgl_glScissor(GLint x, GLint y, GLsizei width, GLsizei height);
WGL_IMPORT("glShaderSource") void wgl_glShaderSource(GLuint shader, GLsizei count, const GLchar** string, const GLint* length);
WGL_IMPORT("glShaderStorageBlockBinding") void wgl_glShaderStorageBlockBinding(GLuint program, GLuint storageBlockIndex, GLuint storageBlockBinding);
WGL_IMPORT("glStencilFunc") void wgl_glStencilFunc(GLenum func, GLint ref, GLuint mask);
WGL_IMPORT("glStencilMask") void wgl_glStencilMask(GLuint mask);
WGL_IMPORT("glStencilOp") void wgl_glStencilOp(GLenum fail, GLenum zfail, GLenum zpass);
WGL_IMPORT("glTexBuffer") void wgl_glTexBuffer(GLenum target, GLenum internalformat, GLuint buffer);
WGL_IMPORT("glTexImage2D") void wgl_glTexImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void* pixels);
WGL_IMPORT("glTexImage3D") void wgl_glTexImage3D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void* pixels);
WGL_IMPORT("glTexParameterf") void wgl_glTexParameterf(GLenum target, GLenum pname, GLfloat param);
WGL_IMPORT("glTexParameterfv") void wgl_glTexParameterfv(GLenum target, GLenum pname, const GLfloat* params);
WGL_IMPORT("glTexParameteri") void wgl_glTexParameteri(GLenum target, GLenum pname, GLint param);
WGL_IMPORT("glTexStorage2D") void wgl_glTexStorage2D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
WGL_IMPORT("glTexStorage3D") void wgl_glTexStorage3D(GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
WGL_IMPORT("glTexSubImage2D") void wgl_glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void* pixels);
WGL_IMPORT("glTexSubImage3D") void wgl_glTexSubImage3D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void* pixels);
WGL_IMPORT("glTextureView") void wgl_glTextureView(GLuint texture, GLenum target, GLuint origtexture, GLenum internalformat, GLuint minlevel, GLuint numlevels, GLuint minlayer, GLuint numlayers);
WGL_IMPORT("glUniform1fv") void wgl_glUniform1fv(GLint location, GLsizei count, const GLfloat* value);
WGL_IMPORT("glUniform1iv") void wgl_glUniform1iv(GLint location, GLsizei count, const GLint* value);
WGL_IMPORT("glUniform1uiv") void wgl_glUniform1uiv(GLint location, GLsizei count, const GLuint* value);
WGL_IMPORT("glUniform2fv") void wgl_glUniform2fv(GLint location, GLsizei count, const GLfloat* value);
WGL_IMPORT("glUniform2iv") void wgl_glUniform2iv(GLint location, GLsizei count, const GLint* value);
WGL_IMPORT("glUniform2uiv") void wgl_glUniform2uiv(GLint location, GLsizei count, const GLuint* value);
WGL_IMPORT("glUniform3fv") void wgl_glUniform3fv(GLint location, GLsizei count, const GLfloat* value);
WGL_IMPORT("glUniform3iv") void wgl_glUniform3iv(GLint location, GLsizei count, const GLint* value);
WGL_IMPORT("glUniform3uiv") void wgl_glUniform3uiv(GLint location, GLsizei count, const GLuint* value);
WGL_IMPORT("glUniform4fv") void wgl_glUniform4fv(GLint location, GLsizei count, const GLfloat* value);
WGL_IMPORT("glUniform4iv") void wgl_glUniform4iv(GLint location, GLsizei count, const GLint* value);
WGL_IMPORT("glUniform4uiv") void wgl_glUniform4uiv(GLint location, GLsizei count, const GLuint* value);
WGL_IMPORT("glUniformMatrix2fv") void wgl_glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
WGL_IMPORT("glUniformMatrix2x3fv") void wgl_glUniformMatrix2x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
WGL_IMPORT("glUniformMatrix2x4fv") void wgl_glUniformMatrix2x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
WGL_IMPORT("glUniformMatrix3fv") void wgl_glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
WGL_IMPORT("glUniformMatrix3x2fv") void wgl_glUniformMatrix3x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
WGL_IMPORT("glUniformMatrix3x4fv") void wgl_glUniformMatrix3x4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
WGL_IMPORT("glUniformMatrix4fv") void wgl_glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
WGL_IMPORT("glUniformMatrix4x2fv") void wgl_glUniformMatrix4x2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
WGL_IMPORT("glUniformMatrix4x3fv") void wgl_glUniformMatrix4x3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
WGL_IMPORT("glUnmapBuffer") GLboolean wgl_glUnmapBuffer(GLenum target);
WGL_IMPORT("glUseProgram") void wgl_glUseProgram(GLuint program);
WGL_IMPORT("glVertexAttrib4f") void wgl_glVertexAttrib4f(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
WGL_IMPORT("glVertexAttrib4fv") void wgl_glVertexAttrib4fv(GLuint index, const GLfloat* v);
WGL_IMPORT("glVertexAttribDivisor") void wgl_glVertexAttribDivisor(GLuint index, GLuint divisor);
WGL_IMPORT("glVertexAttribIPointer") void wgl_glVertexAttribIPointer(GLuint index, GLint size, GLenum type, GLsizei stride, const void* pointer);
WGL_IMPORT("glVertexAttribPointer") void wgl_glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* pointer);
WGL_IMPORT("glViewport") void wgl_glViewport(GLint x, GLint y, GLsizei width, GLsizei height);
}

namespace love {
namespace graphics {
namespace opengl {

// The GL proc-address hook the OpenGL backend calls under
// LOVE_GRAPHICS_GL_STATIC_IMPORTS (its guarded loader seam) in place of
// SDL_GL_GetProcAddress. Returns the address of the matching static import, or
// null for anything the WebGL2 host doesn't provide (glad then leaves that fp_*
// null / its GLAD flag false — the faithful GLES 3.0 profile).
void *getStaticGLProcAddress(const char *name)
{
	static const struct { const char *name; void *fn; } table[] = {
		{"glActiveTexture", (void *)&wgl_glActiveTexture},
		{"glAttachShader", (void *)&wgl_glAttachShader},
		{"glBindAttribLocation", (void *)&wgl_glBindAttribLocation},
		{"glBindBuffer", (void *)&wgl_glBindBuffer},
		{"glBindBufferBase", (void *)&wgl_glBindBufferBase},
		{"glBindFramebuffer", (void *)&wgl_glBindFramebuffer},
		{"glBindImageTexture", (void *)&wgl_glBindImageTexture},
		{"glBindRenderbuffer", (void *)&wgl_glBindRenderbuffer},
		{"glBindTexture", (void *)&wgl_glBindTexture},
		{"glBindVertexArray", (void *)&wgl_glBindVertexArray},
		{"glBlendEquationSeparate", (void *)&wgl_glBlendEquationSeparate},
		{"glBlendFuncSeparate", (void *)&wgl_glBlendFuncSeparate},
		{"glBlitFramebuffer", (void *)&wgl_glBlitFramebuffer},
		{"glBufferData", (void *)&wgl_glBufferData},
		{"glBufferStorage", (void *)&wgl_glBufferStorage},
		{"glBufferSubData", (void *)&wgl_glBufferSubData},
		{"glCheckFramebufferStatus", (void *)&wgl_glCheckFramebufferStatus},
		{"glClear", (void *)&wgl_glClear},
		{"glClearBufferData", (void *)&wgl_glClearBufferData},
		{"glClearBufferSubData", (void *)&wgl_glClearBufferSubData},
		{"glClearBufferfv", (void *)&wgl_glClearBufferfv},
		{"glClearBufferiv", (void *)&wgl_glClearBufferiv},
		{"glClearBufferuiv", (void *)&wgl_glClearBufferuiv},
		{"glClearColor", (void *)&wgl_glClearColor},
		{"glClearDepth", (void *)&wgl_glClearDepth},
		{"glClearDepthf", (void *)&wgl_glClearDepthf},
		{"glClearStencil", (void *)&wgl_glClearStencil},
		{"glClientWaitSync", (void *)&wgl_glClientWaitSync},
		{"glColorMask", (void *)&wgl_glColorMask},
		{"glCompileShader", (void *)&wgl_glCompileShader},
		{"glCompressedTexImage2D", (void *)&wgl_glCompressedTexImage2D},
		{"glCompressedTexImage3D", (void *)&wgl_glCompressedTexImage3D},
		{"glCompressedTexSubImage2D", (void *)&wgl_glCompressedTexSubImage2D},
		{"glCompressedTexSubImage3D", (void *)&wgl_glCompressedTexSubImage3D},
		{"glCopyBufferSubData", (void *)&wgl_glCopyBufferSubData},
		{"glCreateProgram", (void *)&wgl_glCreateProgram},
		{"glCreateShader", (void *)&wgl_glCreateShader},
		{"glCullFace", (void *)&wgl_glCullFace},
		{"glDebugMessageCallback", (void *)&wgl_glDebugMessageCallback},
		{"glDebugMessageControl", (void *)&wgl_glDebugMessageControl},
		{"glDeleteBuffers", (void *)&wgl_glDeleteBuffers},
		{"glDeleteFramebuffers", (void *)&wgl_glDeleteFramebuffers},
		{"glDeleteProgram", (void *)&wgl_glDeleteProgram},
		{"glDeleteRenderbuffers", (void *)&wgl_glDeleteRenderbuffers},
		{"glDeleteShader", (void *)&wgl_glDeleteShader},
		{"glDeleteSync", (void *)&wgl_glDeleteSync},
		{"glDeleteTextures", (void *)&wgl_glDeleteTextures},
		{"glDeleteVertexArrays", (void *)&wgl_glDeleteVertexArrays},
		{"glDepthFunc", (void *)&wgl_glDepthFunc},
		{"glDepthMask", (void *)&wgl_glDepthMask},
		{"glDisable", (void *)&wgl_glDisable},
		{"glDisableVertexAttribArray", (void *)&wgl_glDisableVertexAttribArray},
		{"glDiscardFramebufferEXT", (void *)&wgl_glDiscardFramebufferEXT},
		{"glDispatchCompute", (void *)&wgl_glDispatchCompute},
		{"glDispatchComputeIndirect", (void *)&wgl_glDispatchComputeIndirect},
		{"glDrawArrays", (void *)&wgl_glDrawArrays},
		{"glDrawArraysIndirect", (void *)&wgl_glDrawArraysIndirect},
		{"glDrawArraysInstanced", (void *)&wgl_glDrawArraysInstanced},
		{"glDrawBuffers", (void *)&wgl_glDrawBuffers},
		{"glDrawElements", (void *)&wgl_glDrawElements},
		{"glDrawElementsBaseVertex", (void *)&wgl_glDrawElementsBaseVertex},
		{"glDrawElementsIndirect", (void *)&wgl_glDrawElementsIndirect},
		{"glDrawElementsInstanced", (void *)&wgl_glDrawElementsInstanced},
		{"glEnable", (void *)&wgl_glEnable},
		{"glEnableVertexAttribArray", (void *)&wgl_glEnableVertexAttribArray},
		{"glFenceSync", (void *)&wgl_glFenceSync},
		{"glFinish", (void *)&wgl_glFinish},
		{"glFlush", (void *)&wgl_glFlush},
		{"glFlushMappedBufferRange", (void *)&wgl_glFlushMappedBufferRange},
		{"glFramebufferRenderbuffer", (void *)&wgl_glFramebufferRenderbuffer},
		{"glFramebufferTexture2D", (void *)&wgl_glFramebufferTexture2D},
		{"glFramebufferTexture3D", (void *)&wgl_glFramebufferTexture3D},
		{"glFramebufferTextureLayer", (void *)&wgl_glFramebufferTextureLayer},
		{"glFrontFace", (void *)&wgl_glFrontFace},
		{"glGenBuffers", (void *)&wgl_glGenBuffers},
		{"glGenFramebuffers", (void *)&wgl_glGenFramebuffers},
		{"glGenRenderbuffers", (void *)&wgl_glGenRenderbuffers},
		{"glGenTextures", (void *)&wgl_glGenTextures},
		{"glGenVertexArrays", (void *)&wgl_glGenVertexArrays},
		{"glGenerateMipmap", (void *)&wgl_glGenerateMipmap},
		{"glGetActiveUniform", (void *)&wgl_glGetActiveUniform},
		{"glGetAttribLocation", (void *)&wgl_glGetAttribLocation},
		{"glGetCompressedTextureSubImage", (void *)&wgl_glGetCompressedTextureSubImage},
		{"glGetError", (void *)&wgl_glGetError},
		{"glGetFloatv", (void *)&wgl_glGetFloatv},
		{"glGetIntegerv", (void *)&wgl_glGetIntegerv},
		{"glGetProgramInfoLog", (void *)&wgl_glGetProgramInfoLog},
		{"glGetProgramInterfaceiv", (void *)&wgl_glGetProgramInterfaceiv},
		{"glGetProgramResourceName", (void *)&wgl_glGetProgramResourceName},
		{"glGetProgramiv", (void *)&wgl_glGetProgramiv},
		{"glGetRenderbufferParameteriv", (void *)&wgl_glGetRenderbufferParameteriv},
		{"glGetShaderInfoLog", (void *)&wgl_glGetShaderInfoLog},
		{"glGetShaderiv", (void *)&wgl_glGetShaderiv},
		{"glGetString", (void *)&wgl_glGetString},
		{"glGetTextureSubImage", (void *)&wgl_glGetTextureSubImage},
		{"glGetUniformLocation", (void *)&wgl_glGetUniformLocation},
		{"glHint", (void *)&wgl_glHint},
		{"glInvalidateFramebuffer", (void *)&wgl_glInvalidateFramebuffer},
		{"glLinkProgram", (void *)&wgl_glLinkProgram},
		{"glMapBufferRange", (void *)&wgl_glMapBufferRange},
		{"glMemoryBarrier", (void *)&wgl_glMemoryBarrier},
		{"glObjectLabel", (void *)&wgl_glObjectLabel},
		{"glPixelStorei", (void *)&wgl_glPixelStorei},
		{"glPolygonMode", (void *)&wgl_glPolygonMode},
		{"glPopDebugGroup", (void *)&wgl_glPopDebugGroup},
		{"glPopDebugGroupKHR", (void *)&wgl_glPopDebugGroupKHR},
		{"glPopGroupMarkerEXT", (void *)&wgl_glPopGroupMarkerEXT},
		{"glPushDebugGroup", (void *)&wgl_glPushDebugGroup},
		{"glPushDebugGroupKHR", (void *)&wgl_glPushDebugGroupKHR},
		{"glPushGroupMarkerEXT", (void *)&wgl_glPushGroupMarkerEXT},
		{"glReadBuffer", (void *)&wgl_glReadBuffer},
		{"glReadPixels", (void *)&wgl_glReadPixels},
		{"glRenderbufferStorage", (void *)&wgl_glRenderbufferStorage},
		{"glRenderbufferStorageMultisample", (void *)&wgl_glRenderbufferStorageMultisample},
		{"glResolveMultisampleFramebufferAPPLE", (void *)&wgl_glResolveMultisampleFramebufferAPPLE},
		{"glScissor", (void *)&wgl_glScissor},
		{"glShaderSource", (void *)&wgl_glShaderSource},
		{"glShaderStorageBlockBinding", (void *)&wgl_glShaderStorageBlockBinding},
		{"glStencilFunc", (void *)&wgl_glStencilFunc},
		{"glStencilMask", (void *)&wgl_glStencilMask},
		{"glStencilOp", (void *)&wgl_glStencilOp},
		{"glTexBuffer", (void *)&wgl_glTexBuffer},
		{"glTexImage2D", (void *)&wgl_glTexImage2D},
		{"glTexImage3D", (void *)&wgl_glTexImage3D},
		{"glTexParameterf", (void *)&wgl_glTexParameterf},
		{"glTexParameterfv", (void *)&wgl_glTexParameterfv},
		{"glTexParameteri", (void *)&wgl_glTexParameteri},
		{"glTexStorage2D", (void *)&wgl_glTexStorage2D},
		{"glTexStorage3D", (void *)&wgl_glTexStorage3D},
		{"glTexSubImage2D", (void *)&wgl_glTexSubImage2D},
		{"glTexSubImage3D", (void *)&wgl_glTexSubImage3D},
		{"glTextureView", (void *)&wgl_glTextureView},
		{"glUniform1fv", (void *)&wgl_glUniform1fv},
		{"glUniform1iv", (void *)&wgl_glUniform1iv},
		{"glUniform1uiv", (void *)&wgl_glUniform1uiv},
		{"glUniform2fv", (void *)&wgl_glUniform2fv},
		{"glUniform2iv", (void *)&wgl_glUniform2iv},
		{"glUniform2uiv", (void *)&wgl_glUniform2uiv},
		{"glUniform3fv", (void *)&wgl_glUniform3fv},
		{"glUniform3iv", (void *)&wgl_glUniform3iv},
		{"glUniform3uiv", (void *)&wgl_glUniform3uiv},
		{"glUniform4fv", (void *)&wgl_glUniform4fv},
		{"glUniform4iv", (void *)&wgl_glUniform4iv},
		{"glUniform4uiv", (void *)&wgl_glUniform4uiv},
		{"glUniformMatrix2fv", (void *)&wgl_glUniformMatrix2fv},
		{"glUniformMatrix2x3fv", (void *)&wgl_glUniformMatrix2x3fv},
		{"glUniformMatrix2x4fv", (void *)&wgl_glUniformMatrix2x4fv},
		{"glUniformMatrix3fv", (void *)&wgl_glUniformMatrix3fv},
		{"glUniformMatrix3x2fv", (void *)&wgl_glUniformMatrix3x2fv},
		{"glUniformMatrix3x4fv", (void *)&wgl_glUniformMatrix3x4fv},
		{"glUniformMatrix4fv", (void *)&wgl_glUniformMatrix4fv},
		{"glUniformMatrix4x2fv", (void *)&wgl_glUniformMatrix4x2fv},
		{"glUniformMatrix4x3fv", (void *)&wgl_glUniformMatrix4x3fv},
		{"glUnmapBuffer", (void *)&wgl_glUnmapBuffer},
		{"glUseProgram", (void *)&wgl_glUseProgram},
		{"glVertexAttrib4f", (void *)&wgl_glVertexAttrib4f},
		{"glVertexAttrib4fv", (void *)&wgl_glVertexAttrib4fv},
		{"glVertexAttribDivisor", (void *)&wgl_glVertexAttribDivisor},
		{"glVertexAttribIPointer", (void *)&wgl_glVertexAttribIPointer},
		{"glVertexAttribPointer", (void *)&wgl_glVertexAttribPointer},
		{"glViewport", (void *)&wgl_glViewport},
	};
	for (const auto &e : table)
		if (std::strcmp(e.name, name) == 0)
			return e.fn;
	return nullptr;
}

} // opengl
} // graphics
} // love
